# ============================================================================
# sonar_autofix - Generic auto-fix with GitLab/GitHub integration
# ============================================================================

#' Auto-Fix and Create Merge/Pull Request (GitLab or GitHub)
#'
#' Generic function for automatic code fixes with Git platform integration.
#' Runs [sonar_fix()] to correct code issues, then commits changes and
#' creates a Merge Request (GitLab) or Pull Request (GitHub).
#'
#' @param provider Character. Git platform to use.
#'   `"gitlab"` : create a Merge Request via GitLab API.
#'   `"github"` : create a Pull Request via GitHub CLI (`gh`).
#'   `"auto"`   : auto-detect from CI environment variables.
#'   Default `"auto"`.
#' @param path Path to the R project directory. Default `"."`.
#' @param fixes Fix categories to apply. Passed to [sonar_fix()].
#'   Default `"all"`.
#' @param formatter Formatter to use. Passed to [sonar_fix()].
#'   Default `c("styler", "air")`.
#' @param branch Name of the branch to create for fixes.
#'   Default `"auto/rsonar-fix"`.
#' @param target_branch Target branch for the MR/PR.
#'   Auto-detected from CI if `NULL`.
#' @param commit_message Git commit message.
#' @param mr_title Title of the MR/PR.
#' @param dry_run Logical. If `TRUE`, only simulate without modifying.
#' @param token Authentication token. Auto-detected if empty.
#' @param verbose Logical. Show progress messages.
#'
#' @return Invisibly, a list with `modified`, `branch`, `provider`,
#'   `url`, `files`, `fixes`.
#'
#' @examples
#' \dontrun{
#' sonar_autofix()
#' sonar_autofix(provider = "gitlab")
#' sonar_autofix(dry_run = TRUE)
#' }
#' @export
sonar_autofix <- function(
    provider = c("auto", "gitlab", "github"),
    path = ".",
    fixes = "all",
    formatter = c("styler", "air"),
    branch = "auto/rsonar-fix",
    target_branch = NULL,
    commit_message = "style(rsonar): automatic fixes",
    mr_title = "Automatic fixes generated by rsonar",
    dry_run = FALSE,
    token = "",
    verbose = interactive()) {

  path <- fs::path_abs(path)
  provider <- match.arg(provider)

  if (provider == "auto") {
    if (Sys.getenv("GITLAB_CI", "") != "" ||
        Sys.getenv("CI_PROJECT_ID", "") != "") {
      provider <- "gitlab"
    } else if (Sys.getenv("GITHUB_ACTIONS", "") != "") {
      provider <- "github"
    } else {
      provider <- "gitlab"
    }
  }

  if (verbose) cli::cli_h1("rsonar Auto-Fix ({provider})")

  # Step 1: Run sonar_fix()
  if (verbose) cli::cli_progress_step("Running sonar_fix()")
  fix_res <- sonar_fix(
    path = path, fixes = fixes, formatter = formatter,
    dry_run = dry_run, report = TRUE,
    report_file = "sonar-fixes.json", verbose = FALSE
  )

  total_fixes <- sum(vapply(fix_res$fixes_applied, function(v) {
    if (is.numeric(v) && v > 0) v else 0L
  }, integer(1)))

  if (fix_res$files_modified == 0L) {
    if (verbose) cli::cli_inform(c("v" = "Nothing to fix."))
    return(invisible(list(
      modified = FALSE, branch = NULL, provider = provider,
      url = NULL, files = 0L, fixes = 0L
    )))
  }

  if (dry_run) {
    if (verbose) {
      cli::cli_inform(c("i" = paste0("Would create branch: ", branch)))
    }
    return(invisible(list(
      modified = TRUE, branch = branch, provider = provider,
      url = NULL, files = fix_res$files_modified, fixes = total_fixes
    )))
  }

  # Step 2: Git operations
  target <- target_branch %||%
    Sys.getenv("CI_DEFAULT_BRANCH", Sys.getenv("GITHUB_BASE_REF", "main"))

  git_ok <- tryCatch({
    withr::with_dir(path, {
      system2("git", c("config", "--global", "user.name", "rsonar CI"),
              stdout = FALSE, stderr = FALSE)
      system2("git", c("config", "--global", "user.email", "rsonar@ci.local"),
              stdout = FALSE, stderr = FALSE)

      br_list <- system2("git", c("branch", "-a"), stdout = TRUE, stderr = FALSE)
      if (any(grepl(branch, br_list))) {
        system2("git", c("checkout", "-B", branch),
                stdout = FALSE, stderr = FALSE)
      } else {
        system2("git", c("checkout", "-b", branch),
                stdout = FALSE, stderr = FALSE)
      }
      system2("git", c("add", "."), stdout = FALSE, stderr = FALSE)
      system2("git", c("commit", "-m", commit_message),
              stdout = FALSE, stderr = FALSE)
      system2("git", c("push", "-f", "origin", branch),
              stdout = FALSE, stderr = FALSE)
      TRUE
    })
  }, error = function(e) FALSE)

  if (!git_ok) {
    if (verbose) cli::cli_warn("Git operations failed.")
    return(invisible(list(
      modified = TRUE, branch = NULL, provider = provider,
      url = NULL, files = fix_res$files_modified, fixes = total_fixes
    )))
  }

  # Step 3: Create MR/PR
  url <- NULL
  if (provider == "gitlab") {
    url <- .gl_mr(branch, target, mr_title, token, verbose)
  } else {
    url <- .gh_pr(branch, target, mr_title, token, verbose)
  }

  if (verbose) cli::cli_inform(c("v" = "Auto-fix complete."))
  invisible(list(
    modified = TRUE, branch = branch, provider = provider,
    url = url, files = fix_res$files_modified, fixes = total_fixes
  ))
}


# ---- GitLab connector ----
.gl_mr <- function(branch, target, title, token, verbose) {
  if (token == "" || is.null(token)) token <- Sys.getenv("GITLAB_TOKEN", "")
  if (token == "") token <- Sys.getenv("PERSONAL_ACCESS_TOKEN", "")
  if (token == "") token <- Sys.getenv("CI_JOB_TOKEN", "")
  pid <- Sys.getenv("CI_PROJECT_ID", "")
  api <- Sys.getenv("CI_API_V4_URL",
                    paste0(Sys.getenv("CI_SERVER_URL", "https://gitlab.com"),
                           "/api/v4"))
  if (pid == "" || token == "") return(NULL)

  existing <- tryCatch({
    r <- .gl_api(paste0(api, "/projects/", pid,
                        "/merge_requests?source_branch=", branch,
                        "&state=opened"), token)
    if (length(r) > 0) r[[1]]$iid else NULL
  }, error = function(e) NULL)

  body <- list(
    title = title,
    description = paste0("Auto-generated by rsonar.\nPipeline: ",
                         Sys.getenv("CI_PIPELINE_ID", "?")),
    labels = "rsonar,autofix,quality",
    remove_source_branch = TRUE
  )

  if (!is.null(existing)) {
    r <- tryCatch(
      .gl_api(paste0(api, "/projects/", pid,
                     "/merge_requests/", existing),
              token, "PUT", body)$web_url,
      error = function(e) NULL
    )
    if (verbose && !is.null(r)) {
      cli::cli_inform(c("v" = paste0("MR !", existing, " updated")))
    }
    r
  } else {
    body$source_branch <- branch
    body$target_branch <- target
    r <- tryCatch(
      .gl_api(paste0(api, "/projects/", pid, "/merge_requests"),
              token, "POST", body)$web_url,
      error = function(e) NULL
    )
    if (verbose && !is.null(r)) cli::cli_inform(c("v" = "MR created"))
    r
  }
}

# ---- GitHub connector ----
.gh_pr <- function(branch, target, title, token, verbose) {
  gh <- Sys.which("gh")
  if (gh == "" || nchar(gh) == 0L) return(NULL)
  if (token != "") Sys.setenv(GITHUB_TOKEN = token)
  tryCatch({
    out <- system2(gh, c("pr", "create",
      "--title", title,
      "--body", paste0("Auto-generated by rsonar.\nRun: ",
                       Sys.getenv("GITHUB_RUN_ID", "?")),
      "--head", branch, "--base", target),
      stdout = TRUE, stderr = FALSE)
    if (verbose) cli::cli_inform(c("v" = "PR created"))
    if (length(out) > 0) out[1] else NULL
  }, error = function(e) NULL)
}

# ---- GitLab API helper ----
.gl_api <- function(url, token, method = "GET", body = NULL) {
  tmp <- tempfile("gl-")
  on.exit(unlink(tmp))
  args <- c("-s", "-X", method,
            "--header", paste0("PRIVATE-TOKEN: ", token),
            "--header", "Content-Type: application/json")
  if (!is.null(body)) {
    bf <- tempfile("glb-")
    on.exit(unlink(bf), add = TRUE)
    writeLines(jsonlite::toJSON(body, auto_unbox = TRUE), bf)
    args <- c(args, "--data-binary", paste0("@", bf))
  }
  if (system2("curl", c(args, url), stdout = tmp, stderr = FALSE) != 0) {
    return(list())
  }
  if (!file.exists(tmp) || file.info(tmp)$size == 0) return(list())
  jsonlite::fromJSON(readLines(tmp, warn = FALSE), simplifyVector = FALSE)
}

`%||%` <- function(x, y) if (is.null(x)) y else x