# ============================================================================
# sonar_autofix - Generic auto-fix with GitLab/GitHub integration
# ============================================================================

#' Auto-Fix and Create Merge/Pull Request (GitLab or GitHub)
#'
#' Generic function for automatic code fixes with Git platform integration.
#' Runs [sonar_fix()] to correct code issues, then commits changes and
#' creates a Merge Request (GitLab) or Pull Request (GitHub).
#'
#' @param provider Character. Git platform to use.
#' @param path Path to the R project directory. Default `"."`.
#' @param fixes Fix categories to apply. Default `"all"`.
#' @param formatter Formatter to use. Default `c("styler", "air")`.
#' @param branch Name of the branch to create for fixes. Default `"auto/rsonar-fix"`.
#' @param target_branch Target branch for the MR/PR. Auto-detected from CI.
#' @param commit_message Git commit message.
#' @param mr_title Title of the MR/PR.
#' @param dry_run Logical. If `TRUE`, only simulate without modifying.
#' @param token Authentication token. Auto-detected if empty.
#' @param verbose Logical. Show progress messages.
#' @return Invisibly, a list with results.
#' @export
sonar_autofix <- function(
  provider = c("auto", "gitlab", "github"),
  path = ".",
  fixes = "all",
  formatter = c("styler", "air"),
  branch = "auto/rsonar-fix",
  target_branch = NULL,
  commit_message = "style: automatic fixes by rsonar",
  mr_title = "Automatic fixes generated by rsonar",
  dry_run = FALSE,
  token = "",
  verbose = interactive()
) {
  path <- fs::path_abs(path)
  provider <- match.arg(provider)

  if (provider == "auto") {
    if (Sys.getenv("GITLAB_CI", "") != "" || Sys.getenv("CI_PROJECT_ID", "") != "") {
      provider <- "gitlab"
    } else if (Sys.getenv("GITHUB_ACTIONS", "") != "") {
      provider <- "github"
    } else {
      provider <- "gitlab"
    }
  }

  if (verbose) cli::cli_h1("rsonar Auto-Fix ({provider})")

  # Step 1: Run sonar_fix()
  if (verbose) cli::cli_progress_step("Running sonar_fix()")
  fix_res <- sonar_fix(
    path = path, fixes = fixes, formatter = formatter,
    dry_run = dry_run, report = FALSE,
    verbose = FALSE
  )

  total_fixes <- sum(vapply(fix_res$fixes_applied, function(v) {
    if (is.numeric(v) && v > 0) v else 0L
  }, integer(1)))

  if (fix_res$files_modified == 0L) {
    if (verbose) cli::cli_inform(c("v" = "Nothing to fix."))
    return(invisible(list(modified = FALSE, files = 0L, fixes = 0L)))
  }

  if (dry_run) {
    if (verbose) cli::cli_inform(c("i" = paste("Would create branch:", branch)))
    return(invisible(list(
      modified = TRUE, branch = branch,
      files = fix_res$files_modified, fixes = total_fixes
    )))
  }

  # Step 2: Git push
  target <- target_branch %||% Sys.getenv(
    "CI_DEFAULT_BRANCH",
    Sys.getenv("GITHUB_BASE_REF", "main")
  )

  withr::with_dir(path, {
    system("git config --global user.name 'rsonar CI'")
    system("git config --global user.email 'rsonar@ci.local'")

    br <- system("git branch -a", intern = TRUE)
    if (any(grepl(branch, br))) {
      system(paste("git checkout -B", branch))
    } else {
      system(paste("git checkout -b", branch))
    }

    # ajouter et committer les fichiers modifies (.gitignore exclut les JSON)
    system("git add .")
    r <- system(paste("git commit -m", shQuote(commit_message)), intern = TRUE)
    status <- attr(r, "status")
    if (!is.null(status) && status != 0) {
      cli::cli_abort(c("x" = "git commit failed", "i" = paste(r, collapse = "\n")))
    }

    # Push avec push options GitLab pour creer la MR automatiquement
    if (verbose) cli::cli_progress_step("Pushing branch + creating Merge Request")
    mr_cmd <- paste(
      "git push -f origin", branch,
      "-o merge_request.create",
      paste0("-o merge_request.title=", shQuote(mr_title)),
      paste0(
        "-o merge_request.description=",
        shQuote(paste0("Auto-generated by rsonar. Pipeline: ", Sys.getenv("CI_PIPELINE_ID", "?")))
      ),
      paste0("-o merge_request.target=", target),
      "-o merge_request.label=rsonar",
      "-o merge_request.label=autofix",
      "-o merge_request.label=quality",
      "-o merge_request.remove_source_branch=true"
    )

    system(mr_cmd)
    if (verbose) cli::cli_inform(c("v" = "Merge Request created"))
  })

  # Step 3: Build MR URL
  url <- NULL
  if (provider == "gitlab") {
    proj_url <- Sys.getenv("CI_PROJECT_URL", "")
    if (proj_url != "") {
      url <- paste0(proj_url, "/-/merge_requests")
    }
  } else if (provider == "github") {
    url <- .gh_pr(branch, target, mr_title, token, verbose)
  }

  if (verbose) cli::cli_inform(c("v" = "Auto-fix complete."))
  invisible(list(
    modified = TRUE, branch = branch, provider = provider,
    url = url, files = fix_res$files_modified, fixes = total_fixes
  ))
}

# ---- GitHub connector ----
.gh_pr <- function(branch, target, title, token, verbose) {
  gh <- Sys.which("gh")
  if (gh == "" || nchar(gh) == 0L) {
    return(NULL)
  }
  if (token != "") Sys.setenv(GITHUB_TOKEN = token)
  tryCatch(
    {
      out <- system2(gh, c(
        "pr", "create", "--title", title,
        "--body", paste0("Auto-generated by rsonar.\nRun: ", Sys.getenv("GITHUB_RUN_ID", "?")),
        "--head", branch, "--base", target
      ), stdout = TRUE, stderr = FALSE)
      if (verbose) cli::cli_inform(c("v" = "PR created"))
      if (length(out) > 0) out[1] else NULL
    },
    error = function(e) NULL
  )
}

`%||%` <- function(x, y) if (is.null(x)) y else x
