# ============================================================================
# sonar_autofix - Generic auto-fix with GitLab/GitHub integration
# ============================================================================

#' Auto-Fix and Create Merge/Pull Request (GitLab or GitHub)
#'
#' Generic function for automatic code fixes with Git platform integration.
#' Runs [sonar_fix()] to correct code issues, then commits changes and
#' creates a Merge Request (GitLab) or Pull Request (GitHub).
#'
#' @param provider Character. Git platform to use.
#' @param path Path to the R project directory. Default `"."`.
#' @param fixes Fix categories to apply. Default `"all"`.
#' @param formatter Formatter to use. Default `c("styler", "air")`.
#' @param branch Name of the branch to create for fixes. Default `"auto/rsonar-fix"`.
#' @param target_branch Target branch for the MR/PR. Auto-detected from CI.
#' @param commit_message Git commit message.
#' @param mr_title Title of the MR/PR.
#' @param dry_run Logical. If `TRUE`, only simulate without modifying.
#' @param token Authentication token. Auto-detected if empty.
#' @param verbose Logical. Show progress messages.
#' @return Invisibly, a list with results.
#' @export
sonar_autofix <- function(
    provider = c("auto", "gitlab", "github"),
    path = ".",
    fixes = "all",
    formatter = c("styler", "air"),
    branch = "auto/rsonar-fix",
    target_branch = NULL,
    commit_message = "style: automatic fixes by rsonar",
    mr_title = "Automatic fixes generated by rsonar",
    dry_run = FALSE,
    token = "",
    verbose = interactive()) {
  
  path <- fs::path_abs(path)
  provider <- match.arg(provider)
  
  if (provider == "auto") {
    if (Sys.getenv("GITLAB_CI", "") != "" || Sys.getenv("CI_PROJECT_ID", "") != "") {
      provider <- "gitlab"
    } else if (Sys.getenv("GITHUB_ACTIONS", "") != "") {
      provider <- "github"
    } else {
      provider <- "gitlab"
    }
  }
  
  if (verbose) cli::cli_h1("rsonar Auto-Fix ({provider})")
  
  # Step 1: Run sonar_fix()
  if (verbose) cli::cli_progress_step("Running sonar_fix()")
  fix_res <- sonar_fix(path = path, fixes = fixes, formatter = formatter,
                       dry_run = dry_run, report = TRUE, report_file = "sonar-fixes.json",
                       verbose = FALSE)
  
  total_fixes <- sum(vapply(fix_res$fixes_applied, function(v) {
    if (is.numeric(v) && v > 0) v else 0L
  }, integer(1)))
  
  if (fix_res$files_modified == 0L) {
    if (verbose) cli::cli_inform(c("v" = "Nothing to fix."))
    return(invisible(list(modified = FALSE, files = 0L, fixes = 0L)))
  }
  
  if (dry_run) {
    if (verbose) cli::cli_inform(c("i" = paste("Would create branch:", branch)))
    return(invisible(list(modified = TRUE, branch = branch,
                          files = fix_res$files_modified, fixes = total_fixes)))
  }
  
  # Step 2: Git push
  target <- target_branch %||% Sys.getenv("CI_DEFAULT_BRANCH",
                                          Sys.getenv("GITHUB_BASE_REF", "main"))
  
  withr::with_dir(path, {
    system2("git", c("config", "--global", "user.name", "rsonar CI"),
            stdout = FALSE, stderr = FALSE)
    system2("git", c("config", "--global", "user.email", "rsonar@ci.local"),
            stdout = FALSE, stderr = FALSE)
    
    br <- system2("git", c("branch", "-a"), stdout = TRUE, stderr = FALSE)
    if (any(grepl(branch, br))) {
      system2("git", c("checkout", "-B", branch), stdout = FALSE, stderr = FALSE)
    } else {
      system2("git", c("checkout", "-b", branch), stdout = FALSE, stderr = FALSE)
    }
    system2("git", c("add", "."), stdout = FALSE, stderr = FALSE)
    r <- system2("git", c("commit", "-m", commit_message),
                 stdout = TRUE, stderr = TRUE)
    status <- attr(r, "status")
    if (!is.null(status) && status != 0) {
      cli::cli_abort(c("x" = "git commit failed", "i" = r))
    }
    r <- system2("git", c("push", "-f", "origin", branch),
                 stdout = TRUE, stderr = TRUE)
    status <- attr(r, "status")
    if (!is.null(status) && status != 0) {
      cli::cli_abort(c("x" = "git push failed", "i" = r))
    }
  })
  
  # Step 3: Create MR via API
  url <- NULL
  if (provider == "gitlab") {
    tok <- token
    if (tok == "") tok <- Sys.getenv("GITLAB_TOKEN", "")
    if (tok == "") tok <- Sys.getenv("CI_JOB_TOKEN", "")
    
    pid <- utils::URLencode(Sys.getenv("CI_PROJECT_ID", ""), reserved = TRUE)
    api_url <- Sys.getenv("CI_API_V4_URL",
                          paste0(Sys.getenv("CI_SERVER_URL", "https://gitlab.com"), "/api/v4"))
    
    if (pid != "" && tok != "") {
      if (verbose) cli::cli_progress_step("Creating GitLab Merge Request")
      
      description <- paste0("Auto-generated by rsonar.\nPipeline: ",
                            Sys.getenv("CI_PIPELINE_ID", "?"))
      
      body <- list(
        source_branch = branch,
        target_branch = target,
        title = mr_title,
        description = description,
        labels = "rsonar,autofix,quality",
        remove_source_branch = TRUE)
      
      # Use curl via API
      tmp <- tempfile("gl-")
      on.exit(unlink(tmp))
      body_file <- tempfile("glb-")
      on.exit(unlink(body_file), add = TRUE)
      writeLines(jsonlite::toJSON(body, auto_unbox = TRUE), body_file)
      
      args <- c("-s", "-X", "POST",
                "--header", paste0("PRIVATE-TOKEN: ", tok),
                "--header", "Content-Type: application/json",
                "--data-binary", paste0("@", body_file),
                paste0(api_url, "/projects/", pid, "/merge_requests"))
      
      exit <- system2("curl", args, stdout = tmp, stderr = FALSE)
      if (exit == 0 && file.exists(tmp) && file.info(tmp)$size > 0) {
        resp <- jsonlite::fromJSON(readLines(tmp, warn = FALSE), simplifyVector = FALSE)
        if (!is.null(resp$web_url)) {
          url <- resp$web_url
          if (verbose) cli::cli_inform(c("v" = "MR created: {.url {url}}"))
        } else if (!is.null(resp$message)) {
          if (verbose) cli::cli_warn(paste("GitLab API:", resp$message))
        }
      }
    } else {
      url <- paste0(Sys.getenv("CI_PROJECT_URL", ""), "/-/merge_requests")
      if (verbose && url != "") cli::cli_inform(c("i" = "MR URL: {.url {url}}"))
    }
  } else if (provider == "github") {
    url <- .gh_pr(branch, target, mr_title, token, verbose)
  }
  
  if (verbose) cli::cli_inform(c("v" = "Auto-fix complete."))
  invisible(list(modified = TRUE, branch = branch, provider = provider,
                 url = url, files = fix_res$files_modified, fixes = total_fixes))
}

# ---- GitHub connector ----
.gh_pr <- function(branch, target, title, token, verbose) {
  gh <- Sys.which("gh")
  if (gh == "" || nchar(gh) == 0L) return(NULL)
  if (token != "") Sys.setenv(GITHUB_TOKEN = token)
  tryCatch({
    out <- system2(gh, c("pr", "create", "--title", title,
                         "--body", paste0("Auto-generated by rsonar.\nRun: ", Sys.getenv("GITHUB_RUN_ID", "?")),
                         "--head", branch, "--base", target), stdout = TRUE, stderr = FALSE)
    if (verbose) cli::cli_inform(c("v" = "PR created"))
    if (length(out) > 0) out[1] else NULL
  }, error = function(e) NULL)
}

`%||%` <- function(x, y) if (is.null(x)) y else x